// bublight-webapp/src/main/vue/bublight-webapp/src/components/panel-mode/color-node.component.vue
<template>
    <div :style="{'background-color': nodeColor}" class="color-node"></div>
</template>

<style>
    .color-nodes-list {
        padding: 10px; 
    }

    .color-node { 
        padding: 5px; 
        width: 20px; 
        height: 20px; 
        border-radius: 50%; 
        margin-right: 10px; 
        background-color: #FFF;
        float: left;
        cursor:pointer; 
    }

    .color-picker.no-alpha .color-picker\:a {
      display: none;
    }
</style>

<script>
    export default {
        props: ["color"],

        name: 'color-node',

        data() {
            return {
                nodeColor: this.rgbToHex(this.color)
            }
        },

        watch: {
            color(value) {
                this.nodeColor = this.rgbToHex(value);
            }
        },

        mounted() {
            let picker = new window.CP(this.$el);

            picker.self.classList.add('no-alpha');
            picker.on("change", (r, g, b) => {
                this.$emit("setColor", {red: r, green: g, blue: b});
            });            
        },

        methods: {
            rgbToHex(color) {
                var r = color.red.toString(16)
                var g = color.green.toString(16)
                var b = color.blue.toString(16)

                if (r.length == 1)
                    r = "0" + r
                if (g.length == 1)
                    g = "0" + g
                if (b.length == 1)
                    b = "0" + b

                return "#" + r + g + b
            },
        }
    }
</script>

// lightit-webapp/src/main/angular/lightit-webapp/src/app/components/mode-panel/color-node.component.ts
import { Output, Component, EventEmitter } from '@angular/core';

@Component({
  selector: 'color-node',
  styles: ['.color-nodes-list { padding: 10px; }', '.color-node { padding: 5px; width: 20px; height: 20px; border-radius: 50%; background-color: #FFF; float: left; margin-right: 10px; }'],
  template: `
    <div [style.background]="color"
    [cpPosition]="'top'"
    [cpPositionOffset]="'50%'"
    [cpPositionRelativeToArrow]="true"
    [cpOutputFormat]="rgba"
    (colorPickerChange)="colorPickerChange(color)"
    [(colorPicker)]="color" class="color-node"></div>`
})
export class ColorNodeComponent {
    color: string
    @Output() onSelectValue = new EventEmitter<{ color: string }>()

    colorPickerChange( value: string ) {
        this.color = value
        if (this.color != undefined)
            this.onSelectValue.emit( { color: this.color } )
    }
}
